name: DiamondBank-OG
version: '${version}'
main: net.trueog.diamondbankog.DiamondBankOG
api-version: '${apiVersion}'
commands:
  deposit:
    description: Deposit diamonds into your bank
    usage: /deposit <diamonds> or /deposit all
  withdraw:
    description: Withdraw diamonds from your bank
    usage: /withdraw <diamonds> or /withdraw all
  setbankbalance:
    description: Set the bank balance of a player
    usage: /setbankbalance <player name or player uuid> <shards>
  setbankbal:
    description: Set the bank balance of a player
    usage: /setbankbal <player name or player uuid> <shards>
  pay:
    description: Pay a player
    usage: /pay <player name or player uuid> <diamonds>
  balancetop:
    description: Show the balancetop
    usage: /balancetop <page number (optional)> or /balancetop <player name or player uuid>
  baltop:
    description: Show the balancetop
    usage: /baltop <page number (optional)> or /baltop <player name or player uuid>
  balance:
    description: Get your or someone else's balance
    usage: /balance or /balance <player name or player uuid>
  bal:
    description: Get your or someone else's balance
    usage: /bal or /bal <player name or player uuid>
  diamondbankreload:
    description: Reload the config
    usage: /diamondbankreload
  diamondbankhelp:
    description: DiamondBank help
    usage: /diamondbankhelp
  enableeconomy:
    description: Enable the economy
    usage: /enableeconomy
  disableeconomy:
    description: Disable the economy
    usage: /disableeconomy
  compress:
    description: Compresses every Diamond-related item into the highest value form
    usage: /compress
  autocompress:
    description: Toggles auto-compress, automatically compresses all Diamond currency items in your inventory into the highest value form to save space, mutually exclusive with auto-deposit
    usage: /autocompress
  autodeposit:
    description: Toggles auto-deposit, automatically deposits picked up Diamond currency items, mutually exclusive with auto-compress
    usage: /autodeposit
  dbogtests:
    description: Run the DiamondBank-OG tests, only available in dev builds
    usage: /dbogtests

# So we can overwrite Essentials' commands
softdepend: [ Essentials ]